image: gitlab/dind

services:
  - docker:dind

stages:
  - build
  - deploy
  - test

variables:
  FRONTEND_CONTAINER: "my-react-container" 
  BACKEND_CONTAINER: "my-flask-container"
  FRONTEND_IMAGE: "my-react-image" 
  BACKEND_IMAGE: "my-flask-image"
  COMMON_NETWORK: "my-network"

build_frontend:
  stage: build
  script:
    - cd frontend
    - echo "Building ${FRONTEND_IMAGE}"
    - docker build -t ${FRONTEND_IMAGE} .
    - echo "${FRONTEND_IMAGE} has been built"
    - docker save -o ${FRONTEND_IMAGE}.tar ${FRONTEND_IMAGE}
  artifacts:
    paths:
      - frontend/${FRONTEND_IMAGE}.tar

build_backend:
  stage: build
  script:
    - cd backend
    - echo "Building ${BACKEND_IMAGE}"
    - docker build -t ${BACKEND_IMAGE} .
    - echo "${BACKEND_IMAGE} has been built"
    - docker save -o ${BACKEND_IMAGE}.tar ${BACKEND_IMAGE}
  artifacts:
    paths:
      - backend/${BACKEND_IMAGE}.tar

deploy:
  stage: deploy
  script:
    - echo "Creating a common network"
    - docker network create ${COMMON_NETWORK}
    - echo "Created ${COMMON_NETWORK}"
    - cd backend
    - ls
    - tar xf ${BACKEND_IMAGE}.tar  
    - docker load -i ${BACKEND_IMAGE}.tar
    - echo "Deploying backend container"
    - docker run --name ${BACKEND_CONTAINER} --network ${COMMON_NETWORK} -p 5000:5000 ${BACKEND_IMAGE} || exit 1
    - echo "Backend is now running"
    - cd ../frontend
    - docker load -i ${FRONTEND_IMAGE}.tar
    - echo "Deploying frontend"
    - docker run --name ${FRONTEND_CONTAINER} --network ${COMMON_NETWORK} -p 3000:3000 ${FRONTEND_IMAGE} || exit 1
    - echo "Frontend is now running"

test_backend:
  stage: test
  script:
    - cd backend
    - curl http://localhost:5000/
    - docker exec -it ${BACKEND_CONTAINER} /bin/bash
    - echo "Running tests..."
    - python -m pytest
    - echo "Tests have run"
  artifacts:
    when: always
    paths:
      - test-results/